In [4]:
import numpy as np
import torch

from src.stategen import sample_haar_full
from src.quantum_env import rdm_2q_complex

In [20]:
np.random.seed(5)
psi = sample_haar_full(3)
psi

array([[[ 0.11268154+0.04791048j, -0.08449827-0.08424284j],
        [ 0.62077511-0.30461057j, -0.06437978-0.05232176j]],

       [[ 0.02799238-0.09163844j,  0.40413713+0.15411576j],
        [-0.23220155-0.42515696j, -0.15109333-0.1788131j ]]])

In [21]:
rdms = rdm_2q_complex(np.expand_dims(psi, 0))
rdms.shape

(1, 6, 16)

In [22]:
x = psi.reshape(1, 4, -1)
rdms = x @ np.transpose(x.conj(), [0,2,1])
rdms += np.finfo(rdms.dtype).eps * np.diag([0.0, 1.0, 2.0, 4.0])
rdms

array([[[ 0.02922936+0.j        ,  0.06520357+0.06506806j,
         -0.04836825-0.00935605j, -0.01870346+0.03440159j],
        [ 0.06520357-0.06506806j,  0.48503166+0.j        ,
          0.01120914+0.03713686j,  0.00444553+0.33105143j],
        [-0.04836825+0.00935605j,  0.01120914-0.03713686j,
          0.19625966+0.j        , -0.05615949+0.08215889j],
        [-0.01870346-0.03440159j,  0.00444553-0.33105143j,
         -0.05615949-0.08215889j,  0.28947932+0.j        ]]])

In [23]:
numpy_rhos, numpy_Us = np.linalg.eigh(rdms)
numpy_Us.round(4)

array([[[ 0.9556-0.j    , -0.0432+0.j    , -0.2628+0.j    ,
         -0.1264+0.j    ],
        [-0.141 +0.1387j, -0.4916+0.1558j, -0.1516+0.223j ,
         -0.5826+0.5318j],
        [ 0.2051-0.0663j, -0.3635-0.2305j,  0.8395-0.2334j,
         -0.0707+0.0628j],
        [-0.0361-0.0044j, -0.1785-0.7176j, -0.2951-0.1089j,
          0.4013+0.438j ]]])

In [24]:
torch_rhos, torch_Us = torch.linalg.eigh(torch.from_numpy(rdms))
torch_Us.numpy().round(4)

array([[[-0.9546+0.000e+00j,  0.0608+0.000e+00j,  0.2628+0.000e+00j,
         -0.1264+0.000e+00j],
        [ 0.1516-1.318e-01j,  0.5145-1.000e-04j,  0.1516-2.230e-01j,
         -0.5826+5.318e-01j],
        [-0.2037+7.650e-02j,  0.2832+3.228e-01j, -0.8395+2.334e-01j,
         -0.0707+6.280e-02j],
        [ 0.0255+1.900e-02j, -0.0406+7.386e-01j,  0.2951+1.089e-01j,
          0.4013+4.380e-01j]]])